steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-analysis-api', '-f', 'src/app/api/ml/Dockerfile', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ml-analysis-api']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ml-analysis-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ml-analysis-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '1'
      - '--concurrency'
      - '80'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ml-analysis-api'

# Set timeout to 15 minutes
timeout: '900s' 