services:
  - type: web
    name: simple-timeseries-analysis
    env: python
    plan: free
    rootDir: src/app/api/ml
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1
    domains:
      - simple-timeseries-analysis.onrender.com 