-- Create the sample_data table for storing datasets
CREATE TABLE IF NOT EXISTS sample_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_name TEXT NOT NULL UNIQUE,
    data JSONB NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create an index on dataset_name for faster lookups
CREATE INDEX IF NOT EXISTS idx_sample_data_dataset_name ON sample_data(dataset_name);

-- Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create a trigger to automatically update the updated_at column
DROP TRIGGER IF EXISTS update_sample_data_updated_at ON sample_data;
CREATE TRIGGER update_sample_data_updated_at
BEFORE UPDATE ON sample_data
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Enable row level security
ALTER TABLE sample_data ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access to sample_data
DROP POLICY IF EXISTS "Allow public read access" ON sample_data;
CREATE POLICY "Allow public read access" 
ON sample_data FOR SELECT 
USING (true);

-- Create a policy to allow authenticated users to insert data
DROP POLICY IF EXISTS "Allow authenticated insert" ON sample_data;
CREATE POLICY "Allow authenticated insert" 
ON sample_data FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Create a policy to allow authenticated users to update their own data
DROP POLICY IF EXISTS "Allow authenticated update" ON sample_data;
CREATE POLICY "Allow authenticated update" 
ON sample_data FOR UPDATE 
TO authenticated 
USING (true);

-- Comment on the table and columns
COMMENT ON TABLE sample_data IS 'Table for storing sample datasets for the Time Series Analysis API';
COMMENT ON COLUMN sample_data.dataset_name IS 'Unique name of the dataset';
COMMENT ON COLUMN sample_data.data IS 'JSON data containing the dataset records';
COMMENT ON COLUMN sample_data.description IS 'Description of the dataset'; 